//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDevices.DiskWriter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicDevices.DiskWriter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Physical: .
        /// </summary>
        internal static string Disk_ReadDrive__Physical__ {
            get {
                return ResourceManager.GetString("Disk_ReadDrive__Physical__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Done - Read .
        /// </summary>
        internal static string Disk_ReadDrive_All_Done___Read_ {
            get {
                return ResourceManager.GetString("Disk_ReadDrive_All_Done___Read_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time: .
        /// </summary>
        internal static string Disk_ReadDrive_Elapsed_time__ {
            get {
                return ResourceManager.GetString("Disk_ReadDrive_Elapsed_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading data from drive: .
        /// </summary>
        internal static string Disk_ReadDrive_Error_reading_data_from_drive__ {
            get {
                return ResourceManager.GetString("Disk_ReadDrive_Error_reading_data_from_drive__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading data from drive - past EOF?.
        /// </summary>
        internal static string Disk_ReadDrive_Error_reading_data_from_drive___past_EOF_ {
            get {
                return ResourceManager.GetString("Disk_ReadDrive_Error_reading_data_from_drive___past_EOF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid partitions on drive.
        /// </summary>
        internal static string Disk_ReadDrive_No_valid_partitions_on_drive {
            get {
                return ResourceManager.GetString("Disk_ReadDrive_No_valid_partitions_on_drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with filesystem. It reports it is larger than the disk!.
        /// </summary>
        internal static string Disk_ReadDrive_Problem_with_filesystem__It_reports_it_is_larger_than_the_disk_ {
            get {
                return ResourceManager.GetString("Disk_ReadDrive_Problem_with_filesystem__It_reports_it_is_larger_than_the_disk_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read .
        /// </summary>
        internal static string Disk_ReadDrive_Read_ {
            get {
                return ResourceManager.GetString("Disk_ReadDrive_Read_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  bytes. Elapsed time .
        /// </summary>
        internal static string Disk_WriteDrive__bytes__Elapsed_time_ {
            get {
                return ResourceManager.GetString("Disk_WriteDrive__bytes__Elapsed_time_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  doesn&apos;t exist.
        /// </summary>
        internal static string Disk_WriteDrive__doesn_t_exist {
            get {
                return ResourceManager.GetString("Disk_WriteDrive__doesn_t_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Done - Wrote .
        /// </summary>
        internal static string Disk_WriteDrive_All_Done___Wrote_ {
            get {
                return ResourceManager.GetString("Disk_WriteDrive_All_Done___Wrote_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Disk_WriteDrive_Cancelled {
            get {
                return ResourceManager.GetString("Disk_WriteDrive_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time: .
        /// </summary>
        internal static string Disk_WriteDrive_Elapsed_time__ {
            get {
                return ResourceManager.GetString("Disk_WriteDrive_Elapsed_time__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Couldn&apos;t map partition to physical drive.
        /// </summary>
        internal static string Disk_WriteDrive_Error__Couldn_t_map_partition_to_physical_drive {
            get {
                return ResourceManager.GetString("Disk_WriteDrive_Error__Couldn_t_map_partition_to_physical_drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading zip input stream.
        /// </summary>
        internal static string Disk_WriteDrive_Error_reading_zip_input_stream {
            get {
                return ResourceManager.GetString("Disk_WriteDrive_Error_reading_zip_input_stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing data to drive: .
        /// </summary>
        internal static string Disk_WriteDrive_Error_writing_data_to_drive__ {
            get {
                return ResourceManager.GetString("Disk_WriteDrive_Error_writing_data_to_drive__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing data to drive - past EOF?.
        /// </summary>
        internal static string Disk_WriteDrive_Error_writing_data_to_drive___past_EOF_ {
            get {
                return ResourceManager.GetString("Disk_WriteDrive_Error_writing_data_to_drive___past_EOF_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get device size.
        /// </summary>
        internal static string Disk_WriteDrive_Failed_to_get_device_size {
            get {
                return ResourceManager.GetString("Disk_WriteDrive_Failed_to_get_device_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to lock drive.
        /// </summary>
        internal static string Disk_WriteDrive_Failed_to_lock_drive {
            get {
                return ResourceManager.GetString("Disk_WriteDrive_Failed_to_lock_drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open physical drive.
        /// </summary>
        internal static string Disk_WriteDrive_Failed_to_open_physical_drive {
            get {
                return ResourceManager.GetString("Disk_WriteDrive_Failed_to_open_physical_drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrote .
        /// </summary>
        internal static string Disk_WriteDrive_Wrote_ {
            get {
                return ResourceManager.GetString("Disk_WriteDrive_Wrote_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** WARNING ***.
        /// </summary>
        internal static string MainForm_ButtonReadClick_____WARNING____ {
            get {
                return ResourceManager.GetString("MainForm_ButtonReadClick_____WARNING____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with reading from disk..
        /// </summary>
        internal static string MainForm_ButtonReadClick_Problem_with_reading_from_disk_ {
            get {
                return ResourceManager.GetString("MainForm_ButtonReadClick_Problem_with_reading_from_disk_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Error.
        /// </summary>
        internal static string MainForm_ButtonReadClick_Read_Error {
            get {
                return ResourceManager.GetString("MainForm_ButtonReadClick_Read_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can read from only one drive at a time. Please select only one drive from drive list..
        /// </summary>
        internal static string MainForm_ButtonReadClick_You_can_read_from_only_one_drive_at_a_time {
            get {
                return ResourceManager.GetString("MainForm_ButtonReadClick_You_can_read_from_only_one_drive_at_a_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C: is almost certainly your main hard drive. Writing to this will likely destroy your data, and brick your PC. Are you absolutely sure you want to do this?.
        /// </summary>
        internal static string MainForm_ButtonWriteClick_C__is_almost_certainly_your_main_HDD {
            get {
                return ResourceManager.GetString("MainForm_ButtonWriteClick_C__is_almost_certainly_your_main_HDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem writing to disk. Is it write-protected?.
        /// </summary>
        internal static string MainForm_ButtonWriteClick_Problem_writing_to_disk__Is_it_write_protected_ {
            get {
                return ResourceManager.GetString("MainForm_ButtonWriteClick_Problem_writing_to_disk__Is_it_write_protected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Error.
        /// </summary>
        internal static string MainForm_ButtonWriteClick_Write_Error {
            get {
                return ResourceManager.GetString("MainForm_ButtonWriteClick_Write_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.img,*.bin,*.sdcard)|*.img;*.bin;*.sdcard|Compressed Files (*.zip,*.gz,*tgz)|*.zip;*.gz;*.tgz|All files (*.*)|*.*.
        /// </summary>
        internal static string MainForm_MainForm_Image_Files__Choose {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Image_Files__Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialised. Licensed under GPLv3. Use at own risk!.
        /// </summary>
        internal static string MainForm_MainForm_Initialised__Licensed_under_GPLv3__Use_at_own_risk_ {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Initialised__Licensed_under_GPLv3__Use_at_own_risk_", resourceCulture);
            }
        }
    }
}
