//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicDevices.DiskWriter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicDevices.DiskWriter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** WARNING ***.
        /// </summary>
        internal static string MainForm_ButtonReadClick_____WARNING____ {
            get {
                return ResourceManager.GetString("MainForm_ButtonReadClick_____WARNING____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with reading from disk..
        /// </summary>
        internal static string MainForm_ButtonReadClick_Problem_with_reading_from_disk_ {
            get {
                return ResourceManager.GetString("MainForm_ButtonReadClick_Problem_with_reading_from_disk_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Error.
        /// </summary>
        internal static string MainForm_ButtonReadClick_Read_Error {
            get {
                return ResourceManager.GetString("MainForm_ButtonReadClick_Read_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can read from only one drive at a time. Please select only one drive from drive list..
        /// </summary>
        internal static string MainForm_ButtonReadClick_You_can_read_from_only_one_drive_at_a_time {
            get {
                return ResourceManager.GetString("MainForm_ButtonReadClick_You_can_read_from_only_one_drive_at_a_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C: is almost certainly your main hard drive. Writing to this will likely destroy your data, and brick your PC. Are you absolutely sure you want to do this?.
        /// </summary>
        internal static string MainForm_ButtonWriteClick_C__is_almost_certainly_your_main_HDD {
            get {
                return ResourceManager.GetString("MainForm_ButtonWriteClick_C__is_almost_certainly_your_main_HDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem writing to disk. Is it write-protected?.
        /// </summary>
        internal static string MainForm_ButtonWriteClick_Problem_writing_to_disk__Is_it_write_protected_ {
            get {
                return ResourceManager.GetString("MainForm_ButtonWriteClick_Problem_writing_to_disk__Is_it_write_protected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Error.
        /// </summary>
        internal static string MainForm_ButtonWriteClick_Write_Error {
            get {
                return ResourceManager.GetString("MainForm_ButtonWriteClick_Write_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (*.img,*.bin,*.sdcard)|*.img;*.bin;*.sdcard|Compressed Files (*.zip,*.gz,*tgz)|*.zip;*.gz;*.tgz|All files (*.*)|*.*.
        /// </summary>
        internal static string MainForm_MainForm_Image_Files__Choose {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Image_Files__Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialised. Licensed under GPLv3. Use at own risk!.
        /// </summary>
        internal static string MainForm_MainForm_Initialised__Licensed_under_GPLv3__Use_at_own_risk_ {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Initialised__Licensed_under_GPLv3__Use_at_own_risk_", resourceCulture);
            }
        }
    }
}
